# Generated by Django 3.1.2 on 2020-10-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('sequence', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
                ('protein', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
